# Generated by Django 4.2.15 on 2024-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('AnoDeFundacao', models.DateField()),
                ('vitorias', models.IntegerField()),
                ('titulos', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('posicao', models.CharField(max_length=100)),
                ('clube_atual', models.TextField()),
            ],
        ),
    ]
